ideascube/library/urls.py
from django.conf.urls import url

from . import views


app_name = 'library'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^book/(?P<pk>[\d]+)/$', views.book_detail, name='book_detail'),
    url(r'^book/(?P<pk>[\d]+)/edit/$', views.book_update, name='book_update'),
    url(r'^book/(?P<pk>[\d]+)/delete/$', views.book_delete,
        name='book_delete'),
    url(r'^book/new/$', views.book_create, name='book_create'),
    url(r'^book/export/$', views.book_export, name='book_export'),
    url(r'^book/import/$', views.book_import, name='book_import'),
    url(r'^book/(?P<book_pk>[\d]+)/new-specimen/$', views.specimen_create,
        name='specimen_create'),
    url(r'^specimen/(?P<pk>[\d]+)/edit/$', views.specimen_update,
        name='specimen_update'),
    url(r'^specimen/(?P<pk>[\d]+)/delete/$', views.specimen_delete,
        name='specimen_delete'),
    url(r'^specimen/export/$', views.specimen_export, name='specimen_export'),
    url(r'^specimen/import/$', views.specimen_import, name='specimen_import'),
]

ideascube/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog


from . import views

urlpatterns = i18n_patterns(
    url(r'^blog/', include('ideascube.blog.urls')),
    url(r'^library/', include('ideascube.library.urls')),
    url(r'^search/', include('ideascube.search.urls')),
    url(r'^mediacenter/', include('ideascube.mediacenter.urls')),
    url(r'^monitoring/', include('ideascube.monitoring.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^welcome_staff/$', views.welcome_staff, name='welcome_staff'),
    url(r'^tag/$', views.by_tag, name='by_tag'),
    url(r'^server/', include('ideascube.serveradmin.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={"next_page": "/"},
        name='logout'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/(?P<pk>[\d]+)/$', views.user_detail, name='user_detail'),
    url(r'^user/(?P<pk>[\d]+)/edit/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>[\d]+)/set-password/$', views.set_password,
        name='user_set_password'),
    url(r'^user/new/$', views.user_create, name='user_create'),
    url(r'^user/export/$', views.user_export, name='user_export'),
    url(r'^user/import/$', views.user_import, name='user_import'),
    url(r'^user/(?P<pk>[\d]+)/delete/$',
        views.user_delete, name='user_delete'),
    url(r'^user/(?P<pk>[\d]+)/toggle-staff/$',
        views.user_toggle_staff, name='user_toggle_staff'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['ideascube']), name='jsi18n'),
)
urlpatterns = urlpatterns + [
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideascube/library/models.py
import os

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager

from ideascube.models import (
    LanguageField, SortedTaggableManager, TimeStampedModel)
from ideascube.monitoring.models import StockItem, Specimen
from ideascube.search.models import SearchableQuerySet, SearchMixin


class BookQuerySet(SearchableQuerySet, models.QuerySet):
    def available(self):
        return self.filter(specimens__isnull=False).distinct()


class Book(StockItem, SearchMixin, TimeStampedModel):

    OTHER = 'other'

    SECTION_CHOICES = (
        ('digital', _('digital')),
        ('children-cartoons', _('children - cartoons')),
        ('children-novels', _('children - novels')),
        ('children-poetry', _('children - poetry')),
        ('children-theatre', _('children - theatre')),
        ('children-documentary', _('children - documentary')),
        ('children-comics', _('children - comics')),
        ('children-tales', _('children - tales')),
        ('children-myths', _('chirdren - myths and legends')),
        ('adults-novels', _('adults - novels')),
        ('adults-poetry', _('adults - poetry')),
        ('adults-theatre', _('adults - theatre')),
        ('adults-documentary', _('adults - documentary')),
        ('adults-comics', _('adults - comics')),
        ('adults-tales', _('adults - tales')),
        ('adults-myths', _('adults - myths and legends')),
        ('game', _('game')),
        (OTHER, _('other')),
    )

    KIND_DICT = dict(SECTION_CHOICES)

    # We allow ISBN to be null, but when it is set it needs to be unique.
    isbn = models.CharField(verbose_name=_('isbn'), max_length=40,
                            unique=True, null=True, blank=True)
    authors = models.CharField(verbose_name=_('authors'), max_length=300,
                               blank=True)
    serie = models.CharField(verbose_name=_('serie'), max_length=300,
                             blank=True)
    subtitle = models.CharField(verbose_name=_('subtitle'), max_length=300,
                                blank=True)
    publisher = models.CharField(verbose_name=_('publisher'), max_length=100,
                                 blank=True)
    section = models.CharField(verbose_name=_('section'), max_length=50,
                               choices=SECTION_CHOICES)
    lang = LanguageField(verbose_name=_('Language'), max_length=10)
    cover = models.ImageField(verbose_name=_('cover'),
                              upload_to='library/cover',
                              blank=True)

    objects = BookQuerySet.as_manager()
    tags = TaggableManager(blank=True, manager=SortedTaggableManager)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('library:book_detail', kwargs={'pk': self.pk})

    @property
    def index_strings(self):
        return (self.name, self.isbn, self.authors, self.subtitle,
                self.description, self.serie, u' '.join(self.tags.names()))

    @property
    def index_tags(self):
        return self.tags.slugs()

    @property
    def index_lang(self):
        return self.lang

    @property
    def index_kind(self):
        return self.section

    def save(self, *args, **kwargs):
        self.module = self.LIBRARY

        if self.id is None:
            # This is a new book, without any specimen yet. We make it digital
            # so that it doesn't appear in the stock list.
            self.physical = False

        return super().save(*args, **kwargs)


class BookSpecimen(Specimen, TimeStampedModel):

    location = models.CharField(verbose_name=_('location'), max_length=300,
                                blank=True)
    file = models.FileField(verbose_name=_('digital file'),
                            upload_to='library/digital',
                            blank=True)

    @property
    def physical(self):
        return not bool(self.file)

    def __str__(self):
        if self.physical:
            # barcode is null for digital specimens.
            return u'Specimen {0} of "{1}"'.format(self.barcode, self.item)
        return u'Digital specimen of "{0}"'.format(self.item)

    def get_absolute_url(self):
        return reverse('library:book_detail', kwargs={'pk': self.item.pk})

    @property
    def extension(self):
        if not self.file:
            return ''
        name, extension = os.path.splitext(self.file.name)
        return extension[1:]

    def save(self, *args, **kwargs):
        if self.physical:
            # This is a physical BookSpecimen, make the Book physical
            self.item.physical = True
            self.item.save()

        return super().save(*args, **kwargs)

ideascube/search/models.py
from django.db import models
from django.db.backends.signals import connection_created
from django.db.models.signals import post_save, pre_delete
from django.db.models.base import ModelBase
from django.dispatch import receiver

from .utils import rank
from ..utils import MetaRegistry


class Match(models.Lookup):
    lookup_name = 'match'

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        return '{0} MATCH {1}'.format(lhs, rhs), params


class SearchField(models.Field):
    pass
SearchField.register_lookup(Match)


class TagMatch(models.Lookup):
    lookup_name = 'match'

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        params = params[0]
        if not params:
            # Not tags to match to.
            # Search for stuff with no tag
            params = ['']
        out = '({0} LIKE {1})'.format(lhs, rhs)
        out = ' AND '.join([out]*len(params))
        out = '({})'.format(out)
        return out, ['%|{}|%'.format(p.lower()) for p in params]


class SearchTagField(models.Field):
    pass
SearchTagField.register_lookup(TagMatch)


class SearchQuerySet(models.QuerySet):
    def order_by_relevancy(self):
        extra = {'relevancy': 'rank(matchinfo(idx))'}
        return self.extra(select=extra).order_by('-relevancy')


class Search(models.Model):
    """Model that handle the search."""
    rowid = models.IntegerField(primary_key=True)
    model = models.CharField(max_length=64)
    object_id = models.IntegerField()
    public = models.BooleanField(default=True)
    text = SearchField()
    lang = models.Field()
    kind = models.Field()
    tags = SearchTagField()
    source = models.Field()

    objects = SearchQuerySet.as_manager()

    class Meta:
        db_table = 'idx'
        managed = False

    @classmethod
    def ids(cls, **kwargs):
        qs = Search.objects.filter(**kwargs).order_by_relevancy()
        return qs.values_list('object_id', flat=True)

    @classmethod
    def search(cls, **kwargs):
        qs = Search.objects.filter(**kwargs).order_by_relevancy()
        return (SearchMixin.registered_types[r.model].objects.get(pk=r.object_id) for r in qs)


class MetaSearchMixin(MetaRegistry, ModelBase):
    pass


class SearchMixin(models.Model, metaclass=MetaSearchMixin):
    """Inherit from this mixin to make your model searchable."""

    class Meta:
        abstract = True

    @property
    def index_strings(self):
        return []

    @property
    def index_lang(self):
        return None

    @property
    def index_kind(self):
        return None

    @property
    def index_tags(self):
        return []

    @property
    def index_public(self):
        return True

    @property
    def index_source(self):
        return None

    def is_indexable(self):
        return True

    def index(self):
        if not self.is_indexable():
            return
        text = u" ".join([s for s in self.index_strings if s])
        tags = u"|{}|".format(u"|".join(self.index_tags))
        defaults = {
            'text': text,
            'public': self.index_public,
            'lang': self.index_lang,
            'kind': self.index_kind,
            'source': self.index_source,
            'tags': tags
        }
        Search.objects.update_or_create(
            model=self.__class__.__name__,
            object_id=self.pk,
            defaults=defaults
        )

    def deindex(self):
        Search.objects.filter(
            model=self.__class__.__name__,
            object_id=self.pk).delete()


class SearchableQuerySet(object):
    def search(self, query=None, kind=None, lang=None, tags=[], source=None, **kwargs):
        kwargs['model'] = self.model.__name__
        if query:
            kwargs['text__match'] = query
        if kind:
            kwargs['kind'] = kind
        if lang:
            kwargs['lang'] = lang
        if source:
            kwargs['source'] = source
        if tags:
            kwargs['tags__match'] = tags
        ids = Search.ids(**kwargs).distinct()
        # Force the execution of the request here
        # as we can request on several db in the same time.
        ids = list(ids)
        return self.filter(pk__in=ids)


@receiver(post_save)
def index(sender, instance, **kwargs):
    if issubclass(sender, SearchMixin):
        instance.index()


@receiver(pre_delete)
def deindex(sender, instance, **kwargs):
    if issubclass(sender, SearchMixin):
        instance.deindex()


@receiver(connection_created)
def add_rank_function(sender, connection, **kwargs):
    connection.connection.create_function("rank", 1, rank)

ideascube/library/templates/library/book_card.html
{% load ideascube_tags static %}
<a class="card {% if not book.cover %}default{% endif %} {{ book.section }}" href="{% url 'library:book_detail' pk=book.pk %}">
  <h3>{{ book }}</h3>
  <p>{{ book.authors }}</p>
  {% if book.cover %}
    <img src="{% media book 'cover' %}" class="cover" />
  {% else %}
    <img src="{% static "ideascube/img/default-book.png" %}" class="cover" />
  {% endif %}
</a>

ideascube/library/templates/library/book_confirm_delete.html
{% extends 'form-confirm-delete.html' %}
{% load i18n %}

{% block confirm_message %}
    {% blocktrans %}
         Are you sure you want to delete book "{{ book }}" and all its specimens?
    {% endblocktrans %}
{% endblock %}

{% block cancel_url %}
    {{ book.get_absolute_url }}
{% endblock cancel_url %}

ideascube/library/templates/library/book_detail.html
{% extends 'two-third-third.html' %}
{% load i18n ideascube_tags static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static "library/library.css" %}">
{% endblock %}

{% block twothird %}
    <div class="row mwide twide">
        <div class="col third">
            <h5><a href="{% url 'library:index' %}">&lt; {% trans 'View all books' %}</a></h5>
            {% if book.cover %}<img src="{% media book 'cover' %}" class="cover {{ book.section }}" />{% endif %}
        </div>
        <div class="col two-third book-detail">
            <h4><span class="theme read">{% trans "read" %}</span></h4>
            <h2>{{ book }}</h2>
            {% if book.subtitle %}<h3>{{ book.subtitle }}</h3>{% endif %}
            <hr />
            <p class="flow"><strong>{% trans "Author" %}</strong><span>{{ book.authors }}</span></p>
            <p class="flow"><strong>{% trans "Publisher" %}</strong> <span>{{ book.publisher|default:'—' }}</span></p>
            {% if book.serie %}<p class="flow"><strong>{% trans "Serie" %}</strong> <span>{{ book.serie }}</span></p>{% endif %}
            <hr />
            <p><strong>{% trans "Language" %}</strong> {{ book.get_lang_display }}</p>
            <p><strong>{% trans "ISBN" %}</strong> {{ book.isbn|default:'—' }}</p>
            <hr />
            {% if book.section %}<p class="flow"><strong>{% trans "Section" %}</strong> <span class="{{ book.section }}">{{ book.get_section_display }}</span></p>{% endif %}
            <p>{{ book.description }}</p>
        </div>
    </div>
{% endblock twothird %}
{% block third %}
    {% if user.is_staff %}
    <ul class="card tinted admin">
        <li>{% fa 'plus' 'fa-fw' %} <a href="{% url 'library:specimen_create' book_pk=book.pk %}">{% trans "Add a specimen" %}</a></li>
        <li>{% fa 'trash' 'fa-fw' %} <a href="{% url 'library:book_delete' pk=book.pk %}">{% trans "Delete this book" %}</a></li>
        <li>{% fa 'pencil' 'fa-fw' %} <a href="{% url 'library:book_update' pk=book.pk %}">{% trans "Edit this book" %}</a></li>
    </ul>
    <ul class="card tinted">
        <h4>{% trans "Specimens" %}</h4>
        {% for specimen in book.specimens.all %}
            <li>{% if specimen.instance.physical %}{{ specimen.instance.barcode }}{% else %}{{ specimen.instance.extension }}{% endif %} <a href="{% url 'library:specimen_update' pk=specimen.instance.pk %}" title="{% trans 'Edit specimen' %}">{% fa 'pencil' 'fa-fw' %}</a></li>
        {% empty %}
            {% trans "No specimen for this book." %}
        {% endfor %}
    </ul>
    {% endif %}
    {% if book.specimens.digital %}
    <ul class="card tinted">
        <h4>{% trans "Digital specimens" %}</h4>
        {% for specimen in book.specimens.digital %}
            <li><a href="{% media specimen 'file' %}" title="{% trans 'Download specimen' %}">{% blocktrans with extension=specimen.extension %}Download {{ extension }}{% endblocktrans %} {% fa 'download' 'fa-fw' %}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
    {% tag_cloud url="library:index" model=view.model tags=book.tags.all %}
{% endblock third %}

ideascube/library/templates/library/book_form.html
{% extends 'form-sidebar.html' %}
{% load i18n static ideascube_tags %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "library/library.css" %}">
{% endblock %}

{% block heading %}
    <h2>
        {% if book %}
            {% trans "Edit book" %} "{{ book }}"
        {% else %}
            {% trans "New book" %}
        {% endif %}
    </h2>
{% endblock heading %}

{% block form %}
    <h3>{% trans 'Content' %}</h3>
    {% form_field form.name %}
    {% form_field form.subtitle %}
    {% form_field form.authors %}
    {% form_field form.description %}
    {% form_field form.cover %}
{% endblock form %}

{% block sidebar %}
    <h3>{% trans 'Metadatas' %}</h3>
    {% form_field form.section %}
    {% form_field form.lang %}
    {% form_field form.isbn %}
    {% form_field form.series %}
    {% form_field form.publisher %}
    {% form_field form.tags %}
{% endblock sidebar %}

{% block cancel_url %}
    {% if book %}
        {{ book.get_absolute_url }}
    {% else %}
        {% url 'library:index' %}
    {% endif %}
{% endblock cancel_url %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.stopEnterKey('isbn');
    </script>
{% endblock extra_foot %}

ideascube/library/templates/library/import.html
{% extends 'base.html' %}
{% load i18n static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static "library/library.css" %}">
{% endblock %}

{% block content %}
    <div class="row">
        <h2 class="row wide">{% trans 'Import books notices' %}</h2>
        {% if form.errors %}
            <div class="error">{{ form.errors }}</div>
        {% endif %}
    </div>
    <form method="POST" enctype="multipart/form-data" id="import">
        {% csrf_token %}
        <div class="row">
           <div class="col half">
                <h4>{% trans 'From files' %}</h4>
                <p>{{ form.from_files }}</p>
                <p>{{ form.files_format }}</p>
                <input type="submit" value="{% trans 'Load notices from files' %}" />
            </div>
            <div class="col half">
                <h4>{% trans 'From ISBN' %}</h4>
                <p class="note">{% trans "An Internet connection is needed." %}</p>
                {{ form.from_isbn }}
                <input type="submit" value="{% trans "Load notices from ISBN" %}" />
            </div>
        </div>
    </form>
{% endblock content %}

ideascube/library/templates/library/index.html
{% extends 'two-third-third.html' %}
{% load i18n ideascube_tags static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static "library/library.css" %}">
{% endblock %}

{% block twothird %}
    {% block content_title %}<h2><span class="theme read">{% trans "read" %}</span> {% trans "Library" %}</h2>{% endblock %}
    <div class="pure-g book-list card-container">
        {% for book in book_list  %}
            <div class="pure-u-1 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-4 pure-u">
            {% include 'library/book_card.html' %}
            </div>
        {% empty %}
            <div class="pure-u-1">
            {% trans "No books yet." %}
            </div>
        {% endfor %}
    </div>
    {% include "ideascube/pagination.html" %}
{% endblock twothird %}
{% block third %}
    {% if user.is_staff %}
        <ul class="card tinted admin">
            <li>{% fa 'plus' 'fa-fw' %} <a href="{% url 'library:book_create' %}">{% trans "Add a book" %}</a></li>
            <li>{% fa 'upload' 'fa-fw' %} <a href="{% url 'library:book_import' %}">{% trans "Import notices" %}</a></li>
            <li>{% fa 'download' 'fa-fw' %} <a href="{% url 'library:book_export' %}">{% trans "Export notices" %}</a></li>
            <li>{% fa 'upload' 'fa-fw' %} <a href="{% url 'library:specimen_import' %}">{% trans "Import specimens" %}</a></li>
            <li>{% fa 'download' 'fa-fw' %} <a href="{% url 'library:specimen_export' %}">{% trans "Export specimens" %}</a></li>
        </ul>
    {% endif %}
    {% url 'library:index' as index %}
    {% include 'search/filter_cloud.html' %}
    {% include 'search/box.html' with action=index %}
    {% include 'search/order_by.html' %}
    {% include 'search/filter_by_lang.html' %}
    {% include 'search/filter_by_kind.html' with title=_('by section') %}
    {% tag_cloud url="library:index" model=view.model tags=available_tags %}
{% endblock third %}

ideascube/library/templates/library/specimen_confirm_delete.html
{% extends 'form-confirm-delete.html' %}
{% load i18n %}

{% block confirm_message %}
    {% blocktrans with name=specimen %}
        Are you sure you want to delete "{{ name }}"?
    {% endblocktrans %}
{% endblock %}

{% block confirm_warning %}
    {% blocktrans with name=specimen.item %}
        This will not delete book "{{ name }}"
    {% endblocktrans %}
{% endblock %}

{% block cancel_url %}
    {% url 'library:specimen_update' pk=specimen.instance.pk %}
{% endblock cancel_url %}

ideascube/library/templates/library/specimen_form.html
{% extends 'form-sidebar.html' %}
{% load i18n ideascube_tags %}

{% block heading %}
    <h2>
        {% if specimen %}
            {% blocktrans %}Edit book specimen {{ specimen }}{% endblocktrans %}
        {% elif book %}
            {% blocktrans %}New book specimen for {{ book }}{% endblocktrans %}
        {% else %}
            {% trans "New book specimen" %}
        {% endif %}
    </h2>
{% endblock heading %}

{% block form %}
    {% form_field form.barcode %}
    {% form_field form.comments %}
{% endblock form %}

{% block sidebar %}
    {% form_field form.file %}
    {% form_field form.location %}
    {% form_field form.item %}
{% endblock sidebar %}

{% block cancel_url %}
    {% if specimen %}
        {{ specimen.get_absolute_url }}
    {% elif book %}
        {{ book.get_absolute_url }}
    {% else %}
        {% url 'library:index' %}
    {% endif %}
{% endblock cancel_url %}

{% block extra_form_foot %}
    {% if specimen %}
        <a class="spaced button warning" href="{% url 'library:specimen_delete' pk=specimen.pk %}">{% trans "Delete specimen" %}</a>
    {% endif %}
{% endblock extra_form_foot %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.focusOn('[name=barcode]');
    </script>
{% endblock extra_foot %}

ideascube/library/templates/library/specimen_import.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

    <div>
        <h2>{% trans "Import Book Specimens" %}</h2>
        {% if form.errors %}
            <div class="error">{{ form.errors }}</div>
        {% endif %}
    </div>

    <div>
        <form method="POST" id="import" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="{{ form.source.id_for_label }}">{{ form.source.label }}</label>
            {{ form.source }}
            <input type="submit" value="{% trans 'Import' %}">
        </form>
    </div>

{% endblock content %}