ideascube/serveradmin/urls.py
from django.conf.urls import url

from . import views


app_name = 'server'
urlpatterns = [
    url(r'^settings/$', views.server_info, name='settings'),
    url(r'^power/$', views.power, name='power'),
    url(r'^backup/$', views.backup, name='backup'),
    url(r'^battery/$', views.battery, name='battery'),
    url(r'^wifi/(?P<ssid>.+)?$', views.wifi, name='wifi'),
    url(r'^wifi_history/$', views.wifi_history, name='wifi_history'),
    url(r'^home_page/$', views.home_page, name='home_page'),
    url(r'^languages/$', views.languages, name='languages'),
]

ideascube/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog


from . import views

urlpatterns = i18n_patterns(
    url(r'^blog/', include('ideascube.blog.urls')),
    url(r'^library/', include('ideascube.library.urls')),
    url(r'^search/', include('ideascube.search.urls')),
    url(r'^mediacenter/', include('ideascube.mediacenter.urls')),
    url(r'^monitoring/', include('ideascube.monitoring.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^welcome_staff/$', views.welcome_staff, name='welcome_staff'),
    url(r'^tag/$', views.by_tag, name='by_tag'),
    url(r'^server/', include('ideascube.serveradmin.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={"next_page": "/"},
        name='logout'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/(?P<pk>[\d]+)/$', views.user_detail, name='user_detail'),
    url(r'^user/(?P<pk>[\d]+)/edit/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>[\d]+)/set-password/$', views.set_password,
        name='user_set_password'),
    url(r'^user/new/$', views.user_create, name='user_create'),
    url(r'^user/export/$', views.user_export, name='user_export'),
    url(r'^user/import/$', views.user_import, name='user_import'),
    url(r'^user/(?P<pk>[\d]+)/delete/$',
        views.user_delete, name='user_delete'),
    url(r'^user/(?P<pk>[\d]+)/toggle-staff/$',
        views.user_toggle_staff, name='user_toggle_staff'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['ideascube']), name='jsi18n'),
)
urlpatterns = urlpatterns + [
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideascube/serveradmin/views.py
from subprocess import call

from django.contrib import messages
from django.http import StreamingHttpResponse
from django.shortcuts import render
from django.utils.translation import ugettext as _

from ideascube.configuration import get_config, set_config
from ideascube.decorators import staff_member_required
from ideascube.utils import get_all_languages

from .backup import Backup
from .battery import get_batteries
from .wifi import (
    AvailableWifiNetwork, KnownWifiConnection, enable_wifi, WifiError)

# For unittesting purpose, we need to mock the Catalog class.
# However, the mock is made in a fixture and at this moment, we don't
# know where the mocked catalog will be used.
# So the fixture mocks 'ideascube.serveradmin.catalog.Catalog'.
# If we want to use the mocked Catalog here, we must not import the
# Catalog class directly but reference it from ideascube.serveradmin.catalog
# module.
from . import catalog as catalog_mod


@staff_member_required
def languages(request):
    languages = get_all_languages()

    if request.method == "POST":
        selected = request.POST.getlist('languages')

        if selected:
            set_config(
                'content', 'local-languages', sorted(selected), request.user)

        else:
            messages.error(request, _('Please select at least one language'))

    local_languages = get_config('content', 'local-languages')

    return render(
        request, 'serveradmin/languages.html', {
            'languages': languages, 'selected': local_languages,
        })


@staff_member_required
def power(request):
    if request.POST:
        if 'stop' in request.POST:
            call(["sudo", "poweroff"])
        elif 'restart' in request.POST:
            call(["sudo", "reboot"])

    return render(request, 'serveradmin/power.html')


@staff_member_required
def backup(request):
    if request.POST:
        if 'do_create' in request.POST:
            backup = Backup.create()
            msg = _('Succesfully created backup {filename}').format(
                filename=backup.name
            )
            messages.add_message(request, messages.SUCCESS, msg)
        elif 'do_upload' in request.POST:
            if 'upload' in request.FILES:
                file_ = request.FILES['upload']
                try:
                    backup = Backup.load(file_)
                except Exception as e:
                    msg = _('Unable to load file:')
                    msg = "{msg} {error}".format(msg=msg, error=str(e))
                    messages.add_message(request, messages.ERROR, msg)
                else:
                    msg = _('File {name} has been loaded.').format(
                        name=backup.name)
                    messages.add_message(request, messages.SUCCESS, msg)
            else:
                messages.add_message(request, messages.ERROR,
                                     _('No file found to upload.'))
        elif 'backup' in request.POST:
            backup = Backup(request.POST['backup'])
            msg = None
            if 'do_delete' in request.POST:
                backup.delete()
                msg = _('Succesfully deleted backup {filename}').format(
                    filename=backup.name
                )
            elif 'do_restore' in request.POST:
                backup.restore()
                msg = _('Succesfully restored backup {filename}').format(
                    filename=backup.name
                )
            elif 'do_download' in request.POST:
                response = StreamingHttpResponse(open(backup.path, 'rb'))
                cd = 'attachment; filename="{name}"'.format(name=backup.name)
                response['Content-Disposition'] = cd
                return response
            if msg:
                messages.add_message(request, messages.SUCCESS, msg)
    context = {
        'backups': Backup.list()
    }
    return render(request, 'serveradmin/backup.html', context)


@staff_member_required
def battery(request):
    return render(request, 'serveradmin/battery.html',
                  {'batteries': get_batteries()})


@staff_member_required
def wifi(request, ssid=''):
    try:
        enable_wifi()
        wifi_list = AvailableWifiNetwork.all()

    except WifiError as e:
        messages.error(request, e)
        return render(request, 'serveradmin/wifi.html')

    if ssid:
        try:
            network = wifi_list[ssid]
            wifi_key = request.POST.get('wifi_key', '')
            network.connect(wifi_key=wifi_key)
            messages.success(
                request, _('Connected to {ssid}').format(ssid=ssid))

        except KeyError:
            messages.error(
                request, _('No such network: {ssid}').format(ssid=ssid))

        except WifiError as e:
            messages.error(request, e)

    return render(
        request, 'serveradmin/wifi.html', {'wifi_list': wifi_list.values()})


@staff_member_required
def wifi_history(request):
    try:
        enable_wifi()
        wifi_list = KnownWifiConnection.all()

    except WifiError as e:
        messages.error(request, e)
        return render(request, 'serveradmin/wifi_history.html')

    for ssid, checked in request.POST.items():
        if checked.lower() in ('on', 'true'):
            try:
                connection = wifi_list.pop(ssid)
                connection.forget()

            except KeyError:
                # Someone tried to forget a connection we don't know.
                continue

    return render(
        request, 'serveradmin/wifi_history.html',
        {'wifi_list': wifi_list.values()})


@staff_member_required
def home_page(request):
    if request.POST:
        displayed_packages = request.POST.getlist("displayed")
        set_config('home-page', 'displayed-package-ids',
                   displayed_packages, request.user)
        messages.success(request, _('Home cards updated successfully'))

    catalog = catalog_mod.Catalog()
    installed_packages = catalog.list_installed(['*'])
    displayed_packages = get_config('home-page', 'displayed-package-ids')

    return render(request, 'serveradmin/home_page.html',
        {'installed_packages': installed_packages,
         'displayed_packages': displayed_packages})


@staff_member_required
def server_info(request):
    if request.method == 'POST':
        new_name = request.POST.get('server_name')

        if new_name:
            set_config('server', 'site-name', new_name, request.user)
            messages.success(request, _('Server name changed successfully'))

        else:
            messages.error(request, _('Server name cannot be empty'))

    return render(request, 'serveradmin/settings.html')

ideascube/serveradmin/templates/serveradmin/backup.html
{% extends 'serveradmin/index.html' %}
{% load i18n %}

{% block twothird %}
<h2>{% trans "Manage server backups" %}</h2>
<form name="backups" method="post" enctype="multipart/form-data" id="backup">
    {% csrf_token %}
    <h3>{% trans 'Backup' %}</h3>
    <input type="submit" name="do_create" value="{% trans 'Backup now' %}">
    <hr>
    <h3 id="restore">{% trans 'Restore' %}</h3>
    <table>
        <tr><td></td><th>{% trans 'Source' %}</th><th>{% trans 'Version' %}</th><th>{% trans 'Date' %}</th><th>{% trans 'Size' %}</th><th>{% trans 'Format' %}</th></tr>
    {% for backup in backups %}
        <tr>
            <th><input name="backup" type="radio" value="{{ backup.name }}"></th>
            <td>{{ backup.source }}</td>
            <td>{{ backup.version }}</td>
            <td>{{ backup.date }}</td>
            <td>{{ backup.size|filesizeformat }}</td>
            <td>{{ backup.format }}</td>
        </tr>
    {% endfor %}
    </table>
    <input type="submit" name="do_download" value="{% trans 'Download selected' %}">
    <input type="submit" name="do_restore" value="{% trans 'Restore selected' %}" class="warning">
    <input type="submit" name="do_delete" value="{% trans 'Delete selected' %}" class="warning">
    <hr>
    <h3 id="upload">{% trans 'Upload' %}</h3>
    <input type="file" name="upload">
    <p>{% trans 'File must be a zip, and file name must be in the form {source}-{version}-{date}.zip; eg.: musasa-0.1.0-201501231405.zip' %}</p>
    <input type="submit" name="do_upload" value="{% trans 'Upload backup file' %}">
</form>
{% endblock twothird %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.confirmClick('[name="do_restore"]');
        ID.confirmClick('[name="do_delete"]');
    </script>
{% endblock extra_foot %}

ideascube/serveradmin/templates/serveradmin/battery.html
{% extends 'serveradmin/index.html' %}
{% load i18n ideascube_tags %}

{% block twothird %}
<h2>{% trans "Battery monitoring" %}</h2>
{% for battery in batteries %}
  {% if batteries|length > 1 %}
    <h3>{{ battery.name }}</h3>
  {% endif %}
  <ul>
    <li><strong>{% trans 'Status' %}</strong> {{ battery.status }}</li>
    <li><strong>{% trans 'Capacity' %}</strong> {{ battery.capacity|default:0|min:100 }}%</li>
  </ul>
  {% if not forloop.last %}
    <hr>
  {% endif %}
{% endfor %}
{% endblock twothird %}

ideascube/serveradmin/templates/serveradmin/home_page.html
{% extends 'serveradmin/index.html' %}
{% load i18n %}

{% block twothird %}
<h2>{% trans "Manage home page" %}</h2>
<form name="cards" method="post" id="cards">
    {% csrf_token %}
    <table>
        <tr><th>{% trans 'Card name' %}</th><th>{% trans 'Displayed' %}</th></tr>
        {% for package in installed_packages %}
        <tr>
            <td><label for="package-{{ package.id }}">{{ package.name }} — {{ package.description }}</label></td>
            <td><input id="package-{{ package.id }}" name="displayed" type="checkbox" value="{{ package.id }}" {% if package.id in displayed_packages %}checked{% endif %}/></td>
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="{% trans 'Validate' %}"/>
</form>

{% endblock twothird %}

ideascube/serveradmin/templates/serveradmin/index.html
{% extends 'third-two-third.html' %}

{% load i18n ideascube_tags static %}

{% block extra_head %}
    {% include 'ideascube/includes/form_statics.html' %}
    <link rel="stylesheet" type="text/css" href="{% static "serveradmin/serveradmin.css" %}">
{% endblock extra_head %}

{% block third %}
    <div class="card tinted admin">
        <ul>
            <li>{% fa 'info-circle' 'fa-fw' %} <a href="{% url 'server:settings' %}">{% trans "Server Info" %}</a></li>
            <li>{% fa 'language' 'fa-fw' %} <a href="{% url 'server:languages' %}">{% trans "Languages" %}</a></li>
            <li>{% fa 'power-off' 'fa-fw' %} <a href="{% url 'server:power' %}">{% trans "Restart server" %}</a></li>
            <li>{% fa 'plug' 'fa-fw' %} <a href="{% url 'server:battery' %}">{% trans "Monitor battery" %}</a></li>
            <li>{% fa 'wifi' 'fa-fw' %} <a href="{% url 'server:wifi' %}">{% trans "Manage Wi-Fi" %}</a></li>
            <li>{% fa 'th' 'fa-fw' %} <a href="{% url 'server:home_page' %}">{% trans "Manage home page" %}</a></li>
        </ul>
    </div>
{% endblock third %}

ideascube/serveradmin/templates/serveradmin/languages.html
{% extends 'serveradmin/index.html' %}

{% load i18n %}

{% block twothird %}
<h2>{% trans "Select Languages" %}</h2>

<p>{% trans "Select here the languages which will be available when uploading content" %}</p>

<form id="languages" method="POST" action="">
    {% csrf_token %}

    <fieldset class="list-box" name="languages">

    {% for language_code, language_name in languages %}
        <label class="list-box-item" for="{{ language_code }}">
            <input type="checkbox" id="{{ language_code }}" name="languages" value="{{ language_code }}" {% if language_code in selected %}checked="checked"{% endif %} />
            {{ language_name }} ({{ language_code }})
        </label>
    {% endfor %}

    </fieldset>
    <input type="submit" value="{% trans 'Save' %}" />
</form>

{% endblock %}

ideascube/serveradmin/templates/serveradmin/power.html
{% extends 'serveradmin/index.html' %}
{% load i18n %}

{% block twothird %}
<h2>{% trans "Stop or restart the server" %}</h2>
<form name="server" action="." method="POST">
    {% csrf_token %}
    <input type="submit" name="stop" value="{% trans 'Stop' %}">
    <input type="submit" name="restart" value="{% trans 'Restart' %}">
</form>
{% endblock twothird %}


{% block extra_foot %}
    <script type="text/javascript">
        ID.confirmClick('[name="stop"]');
        ID.confirmClick('[name="restart"]');
    </script>
{% endblock extra_foot %}

ideascube/serveradmin/templates/serveradmin/service_form.html
{% load i18n %}

<div class="status-{% if service.error %}error{% else %}{% if service.status %}on{% else %}off{% endif %}{% endif %}">
    <form id="service-{{ service.name }}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="name" value="{{ service.name }}">
        <h3>{{ service.name }} <span>{% if service.status %}running{% else %}not running{% endif %}</span></h3>
        <p>{{ service.description }}</p>
        {% if service.error %}
            <div class="error">{{ service.error }}</div>
        {% elif service.status %}
            <input type="submit" name="restart" value="{% trans 'Restart' %}">
            <input type="submit" name="stop" value="{% trans 'Stop' %}">
        {% else %}
            <input type="submit" name="start" value="{% trans 'Start' %}">
        {% endif %}
    </form>
</div>

ideascube/serveradmin/templates/serveradmin/settings.html
{% extends 'serveradmin/index.html' %}
{% load i18n %}

{% block twothird %}

    <h2>{% trans 'Server info' %}</h4>

    <ul>
        <li>{% blocktrans with version=IDEASCUBE_VERSION %}Version: {{ version }}{% endblocktrans %}</li>
        <li>{% blocktrans with id=IDEASCUBE_ID %}ID: {{ id }}{% endblocktrans %}</li>
        <li>{% blocktrans with name=IDEASCUBE_HOSTNAME %}Hostname: {{ name }}{% endblocktrans %}</li>
    </ul>

    <hr>

    <h3>{% trans "Change Server Name" %}</h3>

    <form id="server_name" method="POST" action="">
        {% csrf_token %}
        <input type="text" id="server_name" name="server_name" value="{{ server_name }}" />
        <input type="submit" value="{% trans 'Submit' %}" />
    </form>
{% endblock %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.focusOn('[name=server_name]');
    </script>
{% endblock extra_foot %}

ideascube/serveradmin/templates/serveradmin/wifi.html
{% extends 'serveradmin/index.html' %}
{% load i18n %}

{% block twothird %}
<h2>{% trans "Manage Wi-Fi" %}</h2>
{% for wifi in wifi_list %}
{% if forloop.first %}<ul class="list-box">{% endif %}
    <li>
        <a class="list-box-item" data-ssid="{{ wifi.ssid }}" data-known="{{ wifi.known }}" data-secure="{{ wifi.secure }}">
            {{ wifi.ssid }}
            {% if wifi.connected %}
            <span><i class="fa fa-check"></i></span>
            {% endif %}
            <span class="right">{{ wifi.strength }}%</span>
            {% if wifi.secure %}
            <span class="right"><i class="fa fa-lock"></i></span>
            {% endif %}
        </a>
    </li>
{% if forloop.last %}
</ul>
<p><a href="{% url 'server:wifi_history' %}">{% trans 'History' %}</a></p>
{% endif %}
{% empty %}
<p>{% trans 'No Wi-Fi available' %}</p>
{% endfor %}

<div id="passphrase-popup" class="overlay">
    <div class="popup">
        <h2>{% trans 'Authentication required' %}</h2>
        <a class="close" href="#">&times;</a>
        <div class="content">
            <p>{% trans 'An encryption key is required to access this network.' %}</p>
            <form method="POST" action="">
                {% csrf_token %}
                <input type="password" id="wifi_key" name="wifi_key" autocomplete="off" />
                <input type="submit" value="{% trans 'Connect' %}" />
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    ID.initWifiList('.list-box .list-box-item', '#passphrase-popup', "{% url 'server:wifi' %}");

    ID.viewablePassword();
</script>

{% endblock twothird %}

ideascube/serveradmin/templates/serveradmin/wifi_history.html
{% extends 'serveradmin/index.html' %}
{% load i18n %}

{% block twothird %}
<h2>{% trans 'Wi-Fi History' %}</h2>
{% for wifi in wifi_list %}
{% if forloop.first %}
<form method="POST" action="{% url 'server:wifi_history' %}" id="wifi_history">
    {% csrf_token %}
    <fieldset class="list-box" name="ssids">
{% endif %}
        <label class="list-box-item" for="{{ wifi.ssid }}">
            <input type="checkbox" id="{{ wifi.ssid }}" name="{{ wifi.ssid }}" />
            {{ wifi.ssid }}
            {% if wifi.connected %}
            <span><i class="fa fa-check"></i></span>
            {% endif %}
        </label>
{% if forloop.last %}
    </fieldset>
    <input type="submit" value="{% trans 'Forget Selected' %}" />
</form>
{% endif %}
{% empty %}
<p>{% trans 'No known Wi-Fi networks' %}</p>
{% endfor %}

{% endblock twothird %}