ideascube/blog/urls.py
from django.conf.urls import url

from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[\d]+)/$', views.content_detail, name='content_detail'),
    url(r'^(?P<pk>[\d]+)/edit/$', views.content_update, name='content_update'),
    url(r'^new/$', views.content_create, name='content_create'),
]

ideascube/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog


from . import views

urlpatterns = i18n_patterns(
    url(r'^blog/', include('ideascube.blog.urls')),
    url(r'^library/', include('ideascube.library.urls')),
    url(r'^search/', include('ideascube.search.urls')),
    url(r'^mediacenter/', include('ideascube.mediacenter.urls')),
    url(r'^monitoring/', include('ideascube.monitoring.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^welcome_staff/$', views.welcome_staff, name='welcome_staff'),
    url(r'^tag/$', views.by_tag, name='by_tag'),
    url(r'^server/', include('ideascube.serveradmin.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={"next_page": "/"},
        name='logout'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/(?P<pk>[\d]+)/$', views.user_detail, name='user_detail'),
    url(r'^user/(?P<pk>[\d]+)/edit/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>[\d]+)/set-password/$', views.set_password,
        name='user_set_password'),
    url(r'^user/new/$', views.user_create, name='user_create'),
    url(r'^user/export/$', views.user_export, name='user_export'),
    url(r'^user/import/$', views.user_import, name='user_import'),
    url(r'^user/(?P<pk>[\d]+)/delete/$',
        views.user_delete, name='user_delete'),
    url(r'^user/(?P<pk>[\d]+)/toggle-staff/$',
        views.user_toggle_staff, name='user_toggle_staff'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['ideascube']), name='jsi18n'),
)
urlpatterns = urlpatterns + [
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideascube/blog/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager
from taggit.models import TagBase
from unidecode import unidecode

from ideascube.models import (
    LanguageField, SortedTaggableManager, TimeStampedModel)
from ideascube.search.models import SearchableQuerySet, SearchMixin


# Monkeypatch TagBase.slugify, see:
# https://framagit.org/ideascube/ideascube/issues/118
original_slugify = TagBase.slugify


def custom_slugify(self, tag, i=None):
    tag = unidecode(tag)
    return original_slugify(self, tag, i)

TagBase.slugify = custom_slugify


class ContentQuerySet(SearchableQuerySet, models.QuerySet):
    def published(self):
        return self.filter(status=Content.PUBLISHED,
                           published_at__lt=timezone.now())

    def draft(self):
        return self.filter(status=Content.DRAFT)

    def deleted(self):
        return self.filter(status=Content.DELETED)


class Content(SearchMixin, TimeStampedModel, models.Model):

    DRAFT = 1
    PUBLISHED = 2
    DELETED = 3
    STATUSES = (
        (DRAFT, _('draft')),
        (PUBLISHED, _('published')),
        (DELETED, _('deleted')),
    )

    title = models.CharField(verbose_name=_('title'), max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.PROTECT,
                               verbose_name=_('author'))
    summary = models.CharField(
        verbose_name=_('summary'), max_length=300, blank=True)
    image = models.ImageField(verbose_name=_('image'),
                              upload_to='blog/image',
                              blank=True)
    text = models.TextField(verbose_name=_('text'))
    published_at = models.DateTimeField(verbose_name=_('publication date'),
                                        default=timezone.now)
    status = models.PositiveSmallIntegerField(verbose_name=_('Status'),
                                              choices=STATUSES,
                                              default=DRAFT)
    lang = LanguageField(verbose_name=_('Language'), max_length=10,
                         default=settings.LANGUAGE_CODE)

    objects = ContentQuerySet.as_manager()
    tags = TaggableManager(
        blank=True, manager=SortedTaggableManager, verbose_name=_('Topics'))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:content_detail', kwargs={'pk': self.pk})

    @property
    def index_strings(self):
        return (self.title, self.text, str(self.author),
                u' '.join(self.tags.names()))

    @property
    def index_public(self):
        return self.status == self.PUBLISHED

    @property
    def index_tags(self):
        return self.tags.slugs()

    @property
    def index_lang(self):
        return self.lang

ideascube/blog/forms.py
from django import forms

from ideascube.widgets import LangSelect, RichTextEntry

from .models import Content


class ContentForm(forms.ModelForm):
    use_required_attribute = False

    class Meta:
        model = Content
        widgets = {
            "author": forms.HiddenInput,
            # We need a normalized date string for JS datepicker, so we take
            # control over the format to bypass L10N.
            "published_at": forms.DateInput(format='%Y-%m-%d'),
            "lang": LangSelect,
            "summary": RichTextEntry,
            "text": RichTextEntry(with_media=True)
        }
        fields = "__all__"

    def save(self, commit=True):
        content = super().save()
        content.save()  # Index m2m.
        return content

ideascube/blog/views.py
from django.views.generic import (ListView, DetailView, UpdateView, CreateView)
from django.db.models import F
from django.utils.translation import ugettext_lazy as _

from ideascube.mixins import FilterableViewMixin, OrderableViewMixin
from ideascube.decorators import staff_member_required

from .forms import ContentForm
from .models import Content


class Index(FilterableViewMixin, OrderableViewMixin, ListView):

    ORDERS = [
        {
            'key': 'published_at',
            'label': _('Last published'),
            'expression': F('published_at'),
            'sort': 'desc'
        }
    ]

    model = Content
    template_name = 'blog/index.html'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset().exclude(status=Content.DELETED)

        if not self.request.user.is_staff:
            qs = qs.published()

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self._set_available_langs(context)
        self._set_available_tags(context)
        return context

index = Index.as_view()


class ContentDetail(DetailView):
    model = Content

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return Content.objects.all()
        else:
            return Content.objects.published()

content_detail = ContentDetail.as_view()


class ContentUpdate(UpdateView):
    model = Content
    form_class = ContentForm
content_update = staff_member_required(ContentUpdate.as_view())


class ContentCreate(CreateView):
    model = Content
    form_class = ContentForm

    def get_initial(self):
        initial = super().get_initial()
        initial['author'] = self.request.user
        return initial
content_create = staff_member_required(ContentCreate.as_view())

ideascube/blog/templates/blog/content_card.html
{% load ideascube_tags %}

<div class="card blog">
    <a href="{% url 'blog:content_detail' pk=content.pk %}">
        <h3>{{ content }}</h3>
    </a>
    <h5>
        {% if content.status == content.DRAFT %}draft ⚫ {% endif %}
        {{ content.published_at|date:"SHORT_DATE_FORMAT" }} ⚫ {{ content.author }}
    </h5>
    <div>
        {% if content.image %}
            <a href="{% url 'blog:content_detail' pk=content.pk %}">
                <img src="{% media content 'image' %}">
            </a>
        {% endif %}
	{% if content.summary %}
          {{ content.summary|safe }}
	{% else %}
	  {{ content.text|truncatechars_html:300|safe }}
	{% endif %}
    </div>
</div>

ideascube/blog/templates/blog/content_detail.html
{% extends 'two-third-third.html' %}

{% load ideascube_tags i18n %}

{% block twothird %}
    <h5><a href="{% url 'blog:index' %}">&lt; {% trans 'View all posts' %}</a></h5>
    <h2><span class="theme create">{% trans 'Blog' %}</span> {{ content }}</h2>
    <h5>{{ content.published_at|date:"SHORT_DATE_FORMAT" }} ⚫ {{ content.author }}</h5>
    <div class="text">{{ content.text|safe }}</div>
{% endblock twothird %}
{% block third %}
    {% if user.is_staff %}
        <div class="card tinted admin">
            {% fa 'pencil' 'fa-fw' %}<a href="{% url 'blog:content_update' pk=content.pk %}">Edit</a>
        </div>
    {% endif %}
    {% tag_cloud url="blog:index" model=view.model tags=content.tags.all %}
{% endblock third %}

ideascube/blog/templates/blog/content_form.html
{% extends 'form-sidebar.html' %}
{% load i18n ideascube_tags %}

{% block heading %}
    <h2>
        {% if content %}
            {% fa 'pencil' %} {% trans "Edit post" %} "{{ content }}"
        {% else %}
            {% trans "New post" %}
        {% endif %}
    </h2>
{% endblock heading %}

{% block form %}
    <h3>{% trans 'Content' %}</h3>
    {% form_field form.title %}
    {% form_field form.text %}
    {% form_field form.summary %}
{% endblock form %}

{% block sidebar %}
    <h3>{% trans 'Metadatas' %}</h3>
    {% form_field form.author %}
    {% form_field form.image %}
    {% form_field form.published_at %}
    {% form_field form.status %}
    {% form_field form.lang %}
    {% form_field form.tags %}
{% endblock sidebar %}

{% block cancel_url %}
    {% if content %}
        {{ content.get_absolute_url }}
    {% else %}
        {% url 'blog:index' %}
    {% endif %}
{% endblock cancel_url %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.focusOn('[name=title]');
        ID.initDatepicker('published_at');
        ID.initEditors();
    </script>
{% endblock extra_foot %}

ideascube/blog/templates/blog/index.html
{% extends 'two-third-third.html' %}
{% load i18n ideascube_tags %}

{% block twothird %}
    {% block blog_title %}
    <h2><a href="{% url 'blog:index' %}" class="theme create">{% trans 'Blog' %}</a></h2>
    {% endblock blog_title %}
    {% for content in content_list  %}
        {% include 'blog/content_card.html' %}
        <hr />
    {% endfor %}
    {% include "ideascube/pagination.html" %}
{% endblock twothird %}
{% block third %}
    {% if user.is_staff %}
        <div class="card tinted admin">
            {% fa 'plus' 'fa-fw' %} <a href="{% url 'blog:content_create' %}">{% trans "Add content" %}</a>
        </div>
    {% endif %}
    {% url 'blog:index' as index %}
    {% include 'search/filter_cloud.html' %}
    {% include 'search/box.html' with action=index %}
    {% include 'search/order_by.html' %}
    {% include 'search/filter_by_lang.html' %}
    {% tag_cloud url="blog:index" model=view.model tags=available_tags %}
{% endblock third %}