ideascube/mediacenter/urls.py
from django.conf.urls import url

from . import views


app_name = 'mediacenter'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^select/$', views.document_select, name='document_select'),
    url(r'^document/(?P<pk>[\d]+)/$', views.document_detail,
        name='document_detail'),
    url(r'^document/(?P<pk>[\d]+)/edit/$', views.document_update,
        name='document_update'),
    url(r'^document/(?P<pk>[\d]+)/delete/$', views.document_delete,
        name='document_delete'),
    url(r'^document/new/$', views.document_create, name='document_create'),
]

ideascube/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog


from . import views

urlpatterns = i18n_patterns(
    url(r'^blog/', include('ideascube.blog.urls')),
    url(r'^library/', include('ideascube.library.urls')),
    url(r'^search/', include('ideascube.search.urls')),
    url(r'^mediacenter/', include('ideascube.mediacenter.urls')),
    url(r'^monitoring/', include('ideascube.monitoring.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^welcome_staff/$', views.welcome_staff, name='welcome_staff'),
    url(r'^tag/$', views.by_tag, name='by_tag'),
    url(r'^server/', include('ideascube.serveradmin.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={"next_page": "/"},
        name='logout'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/(?P<pk>[\d]+)/$', views.user_detail, name='user_detail'),
    url(r'^user/(?P<pk>[\d]+)/edit/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>[\d]+)/set-password/$', views.set_password,
        name='user_set_password'),
    url(r'^user/new/$', views.user_create, name='user_create'),
    url(r'^user/export/$', views.user_export, name='user_export'),
    url(r'^user/import/$', views.user_import, name='user_import'),
    url(r'^user/(?P<pk>[\d]+)/delete/$',
        views.user_delete, name='user_delete'),
    url(r'^user/(?P<pk>[\d]+)/toggle-staff/$',
        views.user_toggle_staff, name='user_toggle_staff'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['ideascube']), name='jsi18n'),
)
urlpatterns = urlpatterns + [
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideascube/mediacenter/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager

from ideascube.models import (
    LanguageField, SortedTaggableManager, TimeStampedModel)
from ideascube.search.models import SearchableQuerySet, SearchMixin


class DocumentQuerySet(SearchableQuerySet, models.QuerySet):
    def image(self):
        return self.filter(kind=Document.IMAGE)

    def video(self):
        return self.filter(kind=Document.VIDEO)

    def pdf(self):
        return self.filter(kind=Document.PDF)

    def text(self):
        return self.filter(kind=Document.TEXT)

    def audio(self):
        return self.filter(kind=Document.AUDIO)


class Document(SearchMixin, TimeStampedModel):

    IMAGE = 'image'
    VIDEO = 'video'
    PDF = 'pdf'
    EPUB = 'epub'
    MOBI = 'mobi'
    TEXT = 'text'
    AUDIO = 'audio'
    APP = 'app'
    OTHER = 'other'

    KIND_CHOICES = (
        (IMAGE, _('image')),
        (AUDIO, _('sound')),
        (VIDEO, _('video')),
        (PDF, _('pdf')),
        (TEXT, _('text')),
        (EPUB, _('epub')),
        (MOBI, _('mobi')),
        (APP, _('app')),
        (OTHER, _('other')),
    )

    KIND_DICT = dict(KIND_CHOICES)

    title = models.CharField(verbose_name=_('title'), max_length=100)
    summary = models.TextField(verbose_name=_('summary'),
                               blank=True)
    lang = LanguageField(verbose_name=_('Language'), max_length=10, blank=True)
    original = models.FileField(verbose_name=_('Source file'),
                                upload_to='mediacenter/document',
                                max_length=10240,
                                help_text=_('Maximum size : 500 Mo.'))
    preview = models.ImageField(verbose_name=_('Preview picture'),
                                upload_to='mediacenter/preview',
                                max_length=10240,
                                blank=True)
    credits = models.CharField(verbose_name=_('Authorship'),
                               max_length=300,
                               blank=True)
    kind = models.CharField(verbose_name=_('type'),
                            max_length=5,
                            choices=KIND_CHOICES,
                            default=OTHER)

    objects = DocumentQuerySet.as_manager()
    tags = TaggableManager(verbose_name=_('Topics'),
                           blank=True,
                           manager=SortedTaggableManager)

    package_id = models.CharField(verbose_name=_('package'), max_length=100,
                                  blank=True)
    hidden = models.BooleanField(verbose_name=_('hidden'), default=False)

    class Meta:
        ordering = ["-modified_at", ]

    def __str__(self):
        return self.title

    def __repr__(self):
        return '<{}: {}>'.format(self.kind, str(self))

    def get_absolute_url(self):
        return reverse('mediacenter:document_detail', kwargs={'pk': self.pk})

    @property
    def index_strings(self):
        return (self.title, self.summary, self.credits,
                u' '.join(self.tags.names()))

    @property
    def index_lang(self):
        return self.lang

    @property
    def index_kind(self):
        return self.kind

    @property
    def index_source(self):
        return self.package_id

    @property
    def index_tags(self):
        return list(self.tags.slugs()) + list(self.tags.names())

    @property
    def slug(self):
        return self.get_kind_display()

ideascube/mediacenter/forms.py
from django import forms
from django.conf import settings

from ideascube.widgets import LangSelect, RichTextEntry

from .models import Document
from . import utils

import os


class DocumentForm(forms.ModelForm):

    class Meta:
        model = Document
        fields = '__all__'
        widgets = {
            'lang': LangSelect,
            'summary': RichTextEntry
        }
        exclude = ['package_id']

    def clean(self):
        cleaned_data = super().clean()

        kind = cleaned_data['kind']
        original = cleaned_data.get('original')

        if original is None:
            # The 'original' field validator already found this was wrong
            return cleaned_data

        if kind != Document.OTHER:
            return cleaned_data

        try:
            new_kind = utils.guess_kind_from_content_type(original.content_type)
            if not new_kind:
                new_kind = utils.guess_kind_from_extension(original.name)

        except AttributeError:
            # The document was edited without changing its 'original'
            new_kind = utils.guess_kind_from_filename(original.name)

        cleaned_data['kind'] = new_kind or kind

        return cleaned_data

    def save(self, commit=True):
        document = super().save(commit=commit)

        if commit:
            # Need to save a second time to index the m2m
            document.save()

        return document


class CreateDocumentForm(DocumentForm):

    class Meta(DocumentForm.Meta):
        widgets = dict(kind=forms.HiddenInput, **DocumentForm.Meta.widgets)


class PackagedDocumentForm(forms.ModelForm):

    class Meta:
        model = Document
        exclude = ['original', 'preview']

    def __init__(self, path, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['original'] = forms.FilePathField(
            path=path, recursive=True)
        self.fields['preview'] = forms.FilePathField(
            path=path, recursive=True, required=False)

    def save(self, commit=True):
        document = super().save(commit=False)
        original = self.cleaned_data['original']
        original = os.path.relpath(original, settings.MEDIA_ROOT)
        document.original = original

        preview = self.cleaned_data.get('preview', None)
        if preview:
            preview = os.path.relpath(preview, settings.MEDIA_ROOT)
            document.preview = preview

        if commit:
            if not document.id:
                document.save()
            self.save_m2m()
            document.save()
        return document

ideascube/mediacenter/views.py
from django.core.urlresolvers import reverse_lazy
from django.db.models import F
from django.db.models.functions import Lower
from django.utils.translation import get_language, ugettext_lazy as _
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from django.core.exceptions import PermissionDenied

from ideascube.decorators import staff_member_required
from ideascube.mixins import FilterableViewMixin, OrderableViewMixin

# For unittesting purpose, we need to mock the Catalog class.
# However, the mock is made in a fixture and at this moment, we don't
# know where the mocked catalog will be used.
# So the fixture mocks 'ideascube.serveradmin.catalog.Catalog'.
# If we want to use the mocked Catalog here, we must not import the
# Catalog class directly but reference it from ideascube.serveradmin.catalog
# module.
from ideascube.serveradmin import catalog as catalog_mod

from .models import Document
from .forms import CreateDocumentForm, DocumentForm


class NoHiddenDocumentMixin:
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(hidden=False)
        return qs


class Index(NoHiddenDocumentMixin, FilterableViewMixin, OrderableViewMixin, ListView):

    ORDERS = [
        {
            'key': 'modified_at',
            'label': _('Last modification'),
            'expression': F('modified_at'),
            'sort': 'desc'
        },
        {
            'key': 'title',
            'label': _('Title'),
            'expression': Lower('title'),  # Case insensitive.
            'sort': 'asc'
        }
    ]

    model = Document
    template_name = 'mediacenter/index.html'
    paginate_by = 24

    def _set_available_kinds(self, context):
        available_kinds = self._search_for_attr_from_context('kind', context)
        context['available_kinds'] = [
            (kind, label) for kind, label in Document.KIND_CHOICES
            if kind in available_kinds]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self._set_available_kinds(context)
        self._set_available_langs(context)
        self._set_available_tags(context)
        # We assume that if there is a source, it is a package_id.
        package_id = context.get('source')
        if package_id:
            catalog = catalog_mod.Catalog()
            try:
                package = catalog.list_installed([package_id])[0]
            except IndexError:
                # We cannot find the package.
                # This should not happen. Remove the filter
                del context['source']
                return context

            context['source_name'] = package.name
        return context
index = Index.as_view()

class DocumentSelect(Index):
    template_name = 'mediacenter/document_select.html'
document_select = DocumentSelect.as_view()


class DocumentDetail(NoHiddenDocumentMixin, DetailView):
    model = Document
document_detail = DocumentDetail.as_view()


class DocumentUpdate(NoHiddenDocumentMixin, UpdateView):
    model = Document
    form_class = DocumentForm
    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        if object.package_id:
            raise PermissionDenied
        return object
document_update = staff_member_required(DocumentUpdate.as_view())


class DocumentCreate(CreateView):
    model = Document
    form_class = CreateDocumentForm
    initial = {
        'lang': get_language(),
    }
document_create = staff_member_required(DocumentCreate.as_view())


class DocumentDelete(NoHiddenDocumentMixin, DeleteView):
    model = Document
    success_url = reverse_lazy('mediacenter:index')
    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        if object.package_id:
            raise PermissionDenied
        return object
document_delete = staff_member_required(DocumentDelete.as_view())

ideascube/mediacenter/templates/mediacenter/document_card.html
{% load ideascube_tags mediacenter_tags static %}

<a class="card"
   href="{% if url %}{{ url }}{% else %}{{ document.get_absolute_url }}{% endif %}"
   {% if document_insert %}onclick="ID.tinymce_insert_document({{ document_insert }})"{% endif %}
>
  <h3><span class="theme discover">{{ document.slug }}</span> {{ document }}</h3>
  {% if document.preview %}
    <img src="{% media document 'preview' %}" title="{{ document.title }}" />
  {% elif document.kind == document.IMAGE %}
    <img src="{% media document 'original' %}" title="{{ document.title }}" />
  {% else %}
    <img src="{% static document|default_preview_url %}" title="{{ document.title }}" />
  {% endif %}
</a>

ideascube/mediacenter/templates/mediacenter/document_confirm_delete.html
{% extends 'one-row.html' %}
{% load i18n %}

{% block row %}
    <h2>{% blocktrans %}Are you sure you want to delete document "{{ document }}"?{% endblocktrans %}</h2>
    <form method="POST" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="confirm" value="{% trans 'yes' %}" />
    </form>
{% endblock row %}

ideascube/mediacenter/templates/mediacenter/document_detail.html
{% extends 'two-third-third.html' %}

{% load i18n ideascube_tags static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "mediacenter/mediacenter.css" %}">
{% endblock extra_head %}

{% block twothird %}
    <h5><a href="{% url 'mediacenter:index' %}">&lt; {% trans 'View all medias' %}</a></h5>
    <h2><span class="theme discover">{{ document.slug }}</span> {{ document }}</h2>
    {% if document.kind == document.IMAGE %}
        <img src="{% media document 'original' %}" />
    {% elif document.kind == document.VIDEO %}
        <video controls preload="none" width="100%"
            {% if document.preview %}
                poster="{% media document 'preview' %}"
            {% endif %}
        >
            <source src="{% media document 'original' %}">
            {% trans "Your web browser doesn't support this media type." %}
        </video>
    {% elif document.kind == document.AUDIO %}
        <audio controls preload="none" width="100%">
            <source src="{% media document 'original' %}">
            {% trans "Your web browser doesn't support this media type." %}
        </audio>
    {% elif document.preview %}
        <a href="{% media document 'original' %}"><img src="{% media document 'preview' %}" /></a>
    {% endif %}
    <div class="text">{{ document.summary|safe }}</div>
    <div>
        <a class="button" href="{% media document 'original' %}"><span class="fa fa-download fa-fw"></span>
            {% blocktrans with kind=document.KIND_DICT|getitem:document.kind %}
                Download {{ kind }}
            {% endblocktrans %}</a>
    </div>
{% endblock twothird %}
{% block third %}
    {% if user.is_staff %}
        {% if document.package_id %}
            <div class="card tinted admin">
               {% blocktrans with package_id=document.package_id %}
                   Cannot edit or delete this document.
                   It is installed by the "{{ package_id }}" package.
               {% endblocktrans %}
            </div>
        {% else %}
            <ul class="card tinted admin">
                <li>{% fa 'pencil' 'fa-fw' %}<a href="{% url 'mediacenter:document_update' pk=document.pk %}">{% trans 'Edit' %}</a></li>
                <li>{% fa 'trash' 'fa-fw' %}<a href="{% url 'mediacenter:document_delete' pk=document.pk %}">{% trans 'Delete' %}</a></li>
            </ul>
        {% endif %}
    {% endif %}
    {% tag_cloud url="mediacenter:index" model=view.model tags=document.tags.all %}
{% endblock third %}

ideascube/mediacenter/templates/mediacenter/document_form.html
{% extends 'form-sidebar.html' %}
{% load i18n static ideascube_tags %}

{% block heading %}
    <h2>
        {% if document %}
            {% trans "Edit document" %} "{{ document }}"
        {% else %}
            {% trans "New document" %}
        {% endif %}
    </h2>
{% endblock heading %}

{% block form %}
    <h3>{% trans 'Content' %}</h3>
    {% form_field form.title %}
    {% form_field form.original %}
    {% form_field form.summary %}
{% endblock form %}

{% block sidebar %}
    <h3>{% trans 'Metadatas' %}</h3>
    {% form_field form.lang %}
    {% form_field form.kind %}
    {% form_field form.tags %}
    {% form_field form.preview %}
    {% form_field form.credits %}
{% endblock sidebar %}

{% block cancel_url %}
    {% if document %}
        {{ document.get_absolute_url }}
    {% else %}
        {% url 'mediacenter:index' %}
    {% endif %}
{% endblock cancel_url %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.initEditors();
    </script>
{% endblock extra_foot %}

ideascube/mediacenter/templates/mediacenter/document_select.html
{% extends 'two-third-third.html' %}
{% load i18n ideascube_tags mediacenter_tags static %}


{% block header %}{% endblock header %}
{% block footer %}{% endblock footer %}


{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "mediacenter/mediacenter.css" %}">
    <script src="{% url 'jsi18n' %}?version={{ IDEASCUBE_VERSION }}"></script>
    <script src="{% static 'ideascube/js/ideascube.js' %}"></script>
{% endblock %}

{% block body_class %}mediacenter{% endblock %}

{% block twothird %}
    <div class="pure-g document-list card-container">
        {% for document in document_list  %}
            <div class="pure-u-1 pure-u-sm-1-2 pure-u-lg-1-3 pure-u-xl-1-4 pure-u">
            {% include "mediacenter/document_card.html" with document_insert=document|to_json_dict url="#" %}
            </div>
        {% empty %}
            <div class="pure-u-1">
            {% trans "No documents yet." %}
            </div>
        {% endfor %}
    </div>
    {% include "ideascube/pagination.html" %}
{% endblock twothird %}

{% block third %}
    {% include 'search/filter_cloud.html' %}
    {% include 'search/box.html' with action=index %}
    {% include 'search/order_by.html' %}
    {% include 'search/filter_by_kind.html' %}
    {% include 'search/filter_by_lang.html' %}
    {% tag_cloud url='mediacenter:document_select' model=view.model limit=100 tags=available_tags %}
{% endblock third %}

ideascube/mediacenter/templates/mediacenter/index.html
{% extends 'two-third-third.html' %}
{% load i18n ideascube_tags static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "mediacenter/mediacenter.css" %}">
{% endblock %}

{% block body_class %}mediacenter{% endblock %}

{% block twothird %}
    {% block content_title %}<h2><span class="theme discover">{% trans "discover" %}</span> {% trans "Medias Center" %}</h2>{% endblock %}
    <div class="pure-g document-list card-container">
        {% for document in document_list  %}
            <div class="pure-u-1 pure-u-sm-1-2 pure-u-lg-1-3 pure-u-xl-1-4 pure-u">
            {% include "mediacenter/document_card.html" %}
            </div>
        {% empty %}
            <div class="pure-u-1">
            {% trans "No documents yet." %}
            </div>
        {% endfor %}
    </div>
    {% include "ideascube/pagination.html" %}
{% endblock twothird %}
{% block third %}
    {% if user.is_staff %}
        <div class="card tinted admin">
            {% fa 'plus' 'fa-fw' %} <a href="{% url 'mediacenter:document_create' %}">{% trans "Add a document" %}</a>
        </div>
    {% endif %}
    {% url 'mediacenter:index' as index %}
    {% include 'search/filter_cloud.html' %}
    {% include 'search/box.html' with action=index %}
    {% include 'search/order_by.html' %}
    {% include 'search/filter_by_kind.html' %}
    {% include 'search/filter_by_lang.html' %}
    {% tag_cloud url='mediacenter:index' model=view.model limit=100 tags=available_tags %}
{% endblock third %}